on:
    push:
      branches:
        - "main"
  
permissions:
    contents: read
    pages: write
    id-token: write
  
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  
        - name: Install Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16' # använd rätt version av Node.js för ditt projekt
  
        - name: Install dependencies
          run: npm install
  
        - name: Build project
          run: npm run build
  
        - name: Deploy to GitHub Pages
          uses: bitovi/github-actions-react-to-github-pages@v1.2.4
          with:
            path: dist # ändra till rätt byggmapp
  